### PR TITLE
added tests with 76% coverage

### PR DESCRIPTION
**Pull request by krissh-codes**
- removed tsc
- added more exceptions on npmignore
- added tests for all the main functions [76% coverage, 1 failing]
- added jsdoc for getCurrentClass

### CODE REVIEW

**Comment by sank2000** [comment]
I will check this one 👍

**Comment by sank2000** [comment]
test


i fixed that fixed

**Review by sank2000 — APPROVED** [review]

**Comment by krissh-codes** [comment]
> i fixed that fixed

Nice job.

**Review by krissh-codes — COMMENTED** [review]
Merged, so deleting the branch now.

**Pull request merged**
